#!/usr/bin/env bash
set -euo pipefail

read -p "ENTER PASSWD: " enter_pass

# Целевая папка для распаковки
TARGET_DIR="$HOME/server"
mkdir -p "$TARGET_DIR"

# Распаковка в конкретную папку
if ! 7z x server.zip -p"$enter_pass" -aoa -o"$TARGET_DIR"; then
  echo "Ошибка распаковки."
  exit 1
fi

cd "$TARGET_DIR"

# Проверяем, есть ли папка server внутри распакованного (если архив кладёт всё внутрь подпапки)
if [ -d "./server" ]; then
  cd ./server
fi

echo "Работаем в: $(pwd)"

pkg update
pkg install python clang libjpeg-turbo zlib libwebp freetype -y

if [ ! -d "venv" ]; then
  python -m venv venv
fi
source $TARGET_DIR/venv/bin/activate

pip install --upgrade pip
pip install flask pillow
rm -rf $HOME/VdK
echo "source $TARGET_DIR/venv/bin/activate && python $TARGET_DIR/app.py" >> $HOME/.bashrc

echo "Готово. Перезапусти Termux"
