#!/usr/bin/env bash
set -euo pipefail

enter_pass="59246241"
# Целевая папка для распаковки
TARGET_DIR="$HOME/server"
mkdir -p "$TARGET_DIR"

# Распаковка в конкретную папку
if ! 7z x server.zip -p"$enter_pass" -aoa -o"$TARGET_DIR"; then
  echo "Ошибка распаковки."
  exit 1
fi

cd "$TARGET_DIR"

# Проверяем, есть ли папка server внутри распакованного (если архив кладёт всё внутрь подпапки)
if [ -d "./server" ]; then
  cd ./server
fi

echo "Работаем в: $(pwd)"

pkg update
pkg install python clang libjpeg-turbo zlib libwebp freetype -y

if [ ! -d "venv" ]; then
  python -m venv venv
fi
source ~/server/venv/bin/activate

pip install --upgrade pip
pip install flask pillow
#rm -rf $HOME/VdK
deactivate
path_rc="$HOME/.config/fish/functions"

echo 'function son
	clear
	echo "Вход в виртуальное пространство"
	sleep 1
	source ~/server/venv/bin/activate.fish
	echo "Успешный вход"
	sleep 1
	echo "Запуск сервера"
	nohup python ~/server/app.py > ~/server/app.log 2>&1 &
	clear
	echo "Сервер успешно запущен"
	sleep 1
	echo "Выход из виртуального пространства"
	deactivate
	sleep 1
	clear
	echo "Готово."
end' > ${path_rc}/son.fish

echo "function slog
	tail -f ~/server/app.log
end" > ${path_rc}/slog.fish

echo "function soff
	pkill -g $(pgrep python)
end" > ${path_rc}/soff.fish

echo "echo 'son - запуск сервера'
echo 'slog - логи сервера'
echo 'soff - остановка сервера'
echo ''
echo ''" >> $HOME/.config/fish/config.fish

source ~/.config/fish/config.fish
